import pandas as pd
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import os
from scipy.ndimage import gaussian_filter1d

# ==========================================
# [Edit here] Enter the CSV filename generated by the experiment
# ==========================================
TARGET_CSV = "experiment_EMA_Simulation_20260825_162604.csv"
# ==========================================

# PaperPlaza/IEEE-safe PDF fonts: Type 42 TrueType, embedded by Matplotlib.
plt.rcParams.update({
    'pdf.fonttype': 42,
    'pdf.use14corefonts': False,
    'ps.fonttype': 42,
    'ps.useafm': False,
    'text.usetex': False,
    'font.family': 'DejaVu Sans',
    'font.sans-serif': ['DejaVu Sans'],
    'mathtext.fontset': 'dejavusans',
    'axes.unicode_minus': False,
})


def run_visualization():
    output_dir = os.path.join('.', "labF-dynamic")
    csv_path = os.path.join(output_dir, TARGET_CSV)

    if not os.path.exists(csv_path):
        print(f"❌ Data file not found: {csv_path}")
        print("Ensure the experiment ran successfully and TARGET_CSV is configured correctly in this script.")
        return

    print(f"📊 Reading experiment data: {csv_path}")
    df = pd.read_csv(csv_path)

    max_T = len(df)
    robot_num = 3

    # Extract arrays for plotting (keep the reading logic unchanged; only replace MST_Length with Path_Length)
    history_sampled_C_abs = df[['Sensed_C_0', 'Sensed_C_1', 'Sensed_C_2']].values
    history_weights = df[['Weight_0', 'Weight_1', 'Weight_2']].values
    history_path_lengths = df[['Path_Length_0', 'Path_Length_1', 'Path_Length_2']].values

    # ================= Plotting =================
    # Keep the layout compact and share the X axis
    fig, (ax1, ax2, ax3) = plt.subplots(3, 1, figsize=(12, 8), sharex=True)

    # Use different colors for the three robots
    colors = ['#FF6B6B', "#E2AB12", '#45B7D1']

    # Use different line styles for the three robots
    linestyles = ['-', '--', '-.']

    # Use different marker styles for the three robots
    markers = ['o', '*', '^']

    labels = ['Robot A', 'Robot B', 'Robot C']

    # Control marker spacing to avoid excessive density
    mark_every = max(1, max_T // 25)

    # [Larger font] Main figure title
    # fig.suptitle(
    #     'Full Lifecycle Validation: Sensing, Estimation, and Execution',
    #     fontsize=22,
    #     fontweight='bold',
    #     y=0.98
    # )

    # --- Figure 1: Smoothed Noisy Sensor Input ---
    for i in range(robot_num):
        smoothed_noisy_data = gaussian_filter1d(
            history_sampled_C_abs[:, i],
            sigma=1.2
        )

        ax1.plot(
            range(max_T),
            smoothed_noisy_data,
            color=colors[i],
            linestyle=linestyles[i],
            marker=markers[i],
            markevery=mark_every,
            markersize=10,
            markerfacecolor='white',
            markeredgewidth=1.4,
            linewidth=3.5,
            alpha=0.85,
            label=labels[i]
        )

    # [Larger font] Y-axis label and ticks
    ax1.set_ylabel('(a) Coverage \nThroughput(cm/s)', fontsize=18, fontweight='bold')
    ax1.axvline(x=50, color='gray', linestyle=':', linewidth=2)
    ax1.axvline(x=100, color='gray', linestyle=':', linewidth=2)
    plt.setp(ax1.get_yticklabels(), fontweight='bold', fontsize=14)
    ax1.grid(False)

    # --- Figure 2: Weight Estimation via EMA ---
    for i in range(robot_num):
        ax2.plot(
            range(max_T),
            history_weights[:, i],
            color=colors[i],
            linestyle=linestyles[i],
            marker=markers[i],
            markevery=mark_every,
            markersize=10,
            markerfacecolor='white',
            markeredgewidth=1.4,
            linewidth=3.5,
            alpha=0.85
        )

    # [Larger font] Y-axis label and ticks
    ax2.set_ylabel('(b) EMA\nWeight Ratio', fontsize=18, fontweight='bold')
    ax2.axvline(x=50, color='gray', linestyle=':', linewidth=2)
    ax2.axvline(x=100, color='gray', linestyle=':', linewidth=2)

    # [Larger font] Annotations
    ax2.annotate(
        'Initial Equal Weights',
        xy=(0, 0.33),
        xytext=(5, 0.45),
        arrowprops=dict(
            facecolor='black',
            shrink=0.05,
            width=1.5,
            headwidth=6
        ),
        fontweight='bold',
        fontsize=15
    )

    plt.setp(ax2.get_yticklabels(), fontweight='bold', fontsize=14)
    ax2.grid(False)

    # --- Figure 3: Physical Execution (Path Length) ---
    for i in range(robot_num):
        ax3.plot(
            range(max_T),
            history_path_lengths[:, i],
            color=colors[i],
            linestyle=linestyles[i],
            marker=markers[i],
            markevery=mark_every,
            markersize=10,
            markerfacecolor='white',
            markeredgewidth=1.4,
            linewidth=3.5,
            alpha=0.85
        )

    # [Larger font] X/Y-axis labels and ticks
    ax3.set_xlabel('Time Steps', fontsize=18, fontweight='bold')
    ax3.set_ylabel('(c) Path Length', fontsize=18, fontweight='bold')
    ax3.axvline(x=50, color='gray', linestyle=':', linewidth=2)
    ax3.axvline(x=100, color='gray', linestyle=':', linewidth=2)

    plt.setp(ax3.get_xticklabels(), fontweight='bold', fontsize=14)
    plt.setp(ax3.get_yticklabels(), fontweight='bold', fontsize=14)
    ax3.grid(False)

    # [Larger font] Shared legend
    handles, legend_labels = ax1.get_legend_handles_labels()
    fig.legend(
        handles,
        legend_labels,
        loc='upper center',
        ncol=3,
        bbox_to_anchor=(0.5, 0.96),
        frameon=False,
        prop={'size': 16, 'weight': 'bold'},
        labelspacing=0.2,
        borderaxespad=0.0
    )

    # [Spacing adjustment] Keep the width unchanged and reduce the gap between the legend and main plot
    plt.subplots_adjust(
        hspace=0.15,
        top=0.92,
        bottom=0.1,
        left=0.12,
        right=0.95
    )

    base_name = 'Full_Lifecycle_Validation_English_Compact_Bold_LineStyle_Marker'
    save_path_png = os.path.join(output_dir, f'{base_name}.png')
    save_path_pdf = os.path.join(output_dir, f'{base_name}.pdf')

    # Save PNG and PDF in the same directory; pad_inches=0 removes extra whitespace above the legend
    plt.savefig(save_path_png, dpi=300, bbox_inches='tight', pad_inches=0)
    plt.savefig(save_path_pdf, bbox_inches='tight', pad_inches=0)
    print(f"✅ Success! PNG plot saved to: {save_path_png}")
    print(f"✅ Success! PDF plot saved to: {save_path_pdf}")


if __name__ == '__main__':
    run_visualization()
